package com.tinexus.smriti.model;

public enum ActionType {
    SECRET_CREATED,
    SECRET_UPDATED,
    SECRET_DELETED,
    SECRET_VIEWED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    SECRETS_EXPORTED,
    MAGIC_LINK_GENERATED,
    MAGIC_LINK_ACCESSED,
    MAGIC_LINK_REVOKED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_LOGIN_FAILED,
    ROLE_CHANGED,
    BULK_IMPORT_PERFORMED,
    SECRET_ROLLED_BACK,
    GITHUB_SECRETS_SYNCED,
    RENDER_SECRETS_SYNCED,
    SECRET_SCAN_COMPLETED
}
